//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : E-Healthcare-Canada
//  @ File Name : DataDisplay.cpp
//  @ Date : 11/9/2010
//  @ Author : 
//
//


#include "include/DataDisplay.h"


void DataDisplay::DrawHistogram(int SearchObject)
{

}

void DataDisplay::DrawPieChart(int SearchObject)
{

}

void DataDisplay::UpdateMap(int SearchObject)
{

}

/// PUT AN <int> as type to the QList
QList<int> DataDisplay::find(int SearchObject)
{

}

