//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : E-Healthcare-Canada
//  @ File Name : ClientParser.h
//  @ Date : 11/9/2010
//  @ Author : 
//
//


#if !defined(_CLIENTPARSER_H)
#define _CLIENTPARSER_H

#include "../Common/include/Parser.h"


class ClientParser : public Parser
{
public:
    ClientParser();
    bool Parse(QString);

private:



};

#endif  //_CLIENTPARSER_H
