//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : E-Healthcare-Canada
//  @ File Name : ConnectionManagement.h
//  @ Date : 11/9/2010
//  @ Author : 
//
//


#if !defined(_CONNECTIONMANAGEMENT_H)
#define _CONNECTIONMANAGEMENT_H

#include <QTcpSocket>
#include <QString>
#include <QQueue>
#include <QFile>
#include <QStringList>
#include <QMessageBox>
#include <QDebug>
#include "Server.h"
#include "../Common/ReplyObjectHeaders/reply.h"
#include "../Common/ReplyObjectHeaders/loginmsg.h"
#include "../Common/ReplyObjectHeaders/logoutmsg.h"
#include "../Common/ReplyObjectHeaders/loginreply.h"
#include "../Common/ReplyObjectHeaders/logoutreply.h"
#include "../Common/ReplyObjectHeaders/readupdate.h"
#include "../Common/ReplyObjectHeaders/writeupdate.h"
#include "../Common/ReplyObjectHeaders/readupdatereply.h"
#include "../Common/ReplyObjectHeaders/writeupdatereply.h"
#include "include/ListContainer.h"

class Server;

class ConnectionManagement : public QWidget
{
    Q_OBJECT
public:
    ConnectionManagement();
    ConnectionManagement(ListContainer* listContainer);
    ~ConnectionManagement();

    void connectToServer();
    bool disconnectedByClient();

    void handleReadUpdateReply(ReadUpdateReply* readReply, UpdateReply* updateReply);
   // void writeToServer(ReadUpdateReply* readReply, UpdateReply* updateReply);

    bool LoadFile(QString fileName);

    QString getIP();
    int getPort();
    ListContainer* getListContainer();
    void getLatest(int revisionNumber);
    void setMsg(QString msgData);
    void setSID(int sID);

    void setLoginStatus(bool status);

public slots:
    void sendData();
    void readReply();

private slots:
    void error(QAbstractSocket::SocketError error);
    void closeConnection();

private:
    QTcpSocket socket;
    Server* server;
    ListContainer* container;
    Parser p;
    QString IP;
    int PORT;
    bool loggedIn; //static?
    QString msg;
    int sessionID;
};

#endif  //_CONNECTIONMANAGEMENT_H
