//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : E-Healthcare-Canada
//  @ File Name : DataDisplay.h
//  @ Date : 11/9/2010
//  @ Author : 
//
//


#if !defined(_DATADISPLAY_H)
#define _DATADISPLAY_H

#include <QList>

class DataDisplay
{
public:
	void DrawHistogram(int SearchObject);
	void DrawPieChart(int SearchObject);
	void UpdateMap(int SearchObject);
        QList<int> find(int SearchObject);
};

#endif  //_DATADISPLAY_H
