//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : E-Healthcare-Canada
//  @ File Name : DiseaseCriteria.h
//  @ Date : 11/9/2010
//  @ Author : 
//
//
//////////////////////////////////////FUNCTION///////////////////////////////////////////////////////////////////
//this item is used to store all of the search criteria the the program needs to find items inside of the list container
//add any criteria you want into the instance and pass it to the search function of the list container
//if any of the fields fields are not set or empty then the search will assume the searcher doesnt care about that
//field
////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "../Common/include/City.h"

#include <QDate>
#include <QString>
#include <QList>
#if !defined(_DISEASECRITERIA_H)
#define _DISEASECRITERIA_H

//#include "SearchCriteria.h"
//search criteria for disease cases
class DiseaseCriteria
{
public:
    DiseaseCriteria();

    bool addDiseaseTypeList(QList<int> listToAdd);
    void addDiseaseType(int diseaseToAdd);
    QList<int> getDiseaseTypeList();
    QList<QString> getDiseaseTypeNames();


    void addDiseaseType(QString diseaseName);


    QDate getStartDate();
    bool setStartDate(QDate newStartDate);

    QDate getEndDate();
    bool setEndDate(QDate newEndDate);


    bool addCity(City* cityToAdd);
    QList<City*> getLocationList();
    bool addCity(QString cityName);
    QList<QString> getCityNames();
    QString print();



    int getMinQuantity();
    int getMaxQuantity();
    bool setMaxQuantity(int newMax);
    bool setMinQuantity(int newMin);
private:
    int minQuantity;
    int maxQuantity;

    QList<City*> locations;
    QList<QString> cityNames;
    QList<int> types;
    QList<QString> typeNames;
    QDate startDate;
    QDate endDate;



};

#endif  //_DISEASECRITERIA_H
