//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : E-Healthcare-Canada
//  @ File Name : QList.h
//  @ Date : 11/9/2010
//  @ Author : 
//
//


#if !defined(_QLIST_H)
#define _QLIST_H


class QList
{
};

#endif  //_QLIST_H
