//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : E-Healthcare-Canada
//  @ File Name : SearchCriteria.h
//  @ Date : 11/9/2010
//  @ Author : 
//
//


#if !defined(_SEARCHCRITERIA_H)
#define _SEARCHCRITERIA_H

#include <QList>

class SearchCriteria
{
public:
        SearchCriteria();
        //QList<QString> Location;
        //int min;
        //int max;
        //QList<int> TypeID;
        //bool isModeled;
};

#endif  //_SEARCHCRITERIA_H
