//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : E-Healthcare-Canada
//  @ File Name : ShipmentCriteria.h
//  @ Date : 11/9/2010
//  @ Author : 
//
//
//////////////////////////////////////FUNCTION///////////////////////////////////////////////////////////////////
//this item is used to store all of the search criteria the the program needs to find items inside of the list container
//add any criteria you want into the instance and pass it to the search function of the list container
//if any of the fields fields are not set or empty then the search will assume the searcher doesnt care about that
//field
////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#if !defined(_SHIPMENTCRITERIA_H)
#define _SHIPMENTCRITERIA_H


#include "../Common/include/Shipment.h"
#include "../Common/include/City.h"
#include <QDate>
#include <QString>
#include <QList>
class ShipmentCriteria
{
public:
    ShipmentCriteria();

    bool addSenders(QList<City*> citiesToAdd);
    bool addSender(City* cityToAdd);

    QList<City*> getSenderList();

    bool addSender(QString cityName);
    QList<QString> getSenderCityNames();

    bool addDestinations(QList<City*> citiesToAdd);
    bool addDestination(City* cityToAdd);
    QList<City*> getDestinationList();

    bool addDestination(QString cityName);
    QList<QString> getDestinationCityNames();

    bool addTypes(QList<int> typesToAdd);
    bool addType(int typeToAdd);
    QList<int> getTypeList();

    bool addType(QString typeToAdd);
    QList<QString> getTypeNames();

    bool addShipmentStatus(Shipment::SHIPMENT_STATUS newStatus);
    QList<Shipment::SHIPMENT_STATUS> getStatus();

    bool setStartDate(QDate newStartDate);
    QDate getStartDate();

    bool setEndDate(QDate newEndDate);
    QDate getEndDate();

    bool setMaxQuantity(int newMax);
    int getMinQuantity();

    bool setMinQuantity(int newMin);
    int getMaxQuantity();

private:

        QList<City*> senders;
        QList<QString> senderCityNames;
        QList<City*> destinations;
        QList<QString> destinationCityNames;
        QList<int> types;
        QList<QString> typeNames;
        int minQuantity;
        int maxQuantity;

        QDate startDate;//checks for anything after this date
        QDate endDate;//checks for anything before this date

        QList<Shipment::SHIPMENT_STATUS> status;
};

#endif  //_SHIPMENTCRITERIA_H
