//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : E-Healthcare-Canada
//  @ File Name : UIDrawHelper.h
//  @ Date : 11/9/2010
//  @ Author : 
//
//


#if !defined(_UIDRAWHELPER_H)
#define _UIDRAWHELPER_H

#include <QList>
#include <marble/MarbleWidget.h>
#include <marble/MarbleMap.h>
#include <marble/MarbleModel.h>
#include <marble/GeoPainter.h>
#include <marble/LayerInterface.h>
#include <marble/GeoDataGeometry.h>
#include <marble/GeoDataPolygon.h>
#include <marble/GeoDataStyle.h>

#include <QtGui/QApplication>
#include <QtGui/QKeyEvent>
#include <QTime>
#include <QStringList>
#include <include/Model.h>

using namespace Marble;

class UIDrawHelper  : public QObject, public LayerInterface
{
public:
    UIDrawHelper( MarbleWidget *marbleWidget );
    UIDrawHelper( MarbleWidget *marbleWidget, GeoDataCoordinates coord );
    virtual QStringList renderPosition() const;


    virtual bool render( GeoPainter *painter, ViewportParams *viewPort,
                         const QString &renderPos = "NONE", GeoSceneLayer *layer = 0);

    virtual bool eventFilter( QObject *object, QEvent *event );

    void setCoordinatesSupplies( GeoDataCoordinates geo );
    void setCoordinatesCases( GeoDataCoordinates geo );
    void setCoordinatesSupplies( GeoDataCoordinates geo, QColor color );
    void setCoordinatesCases( GeoDataCoordinates geo, QColor color );
    void setCoordinates( float lat, float lon );
    void setCoordinates( Model *tModel, const QString geo );
    const GeoDataCoordinates getCoordinates();

    GeoDataCoordinates approximate(const GeoDataCoordinates &base, qreal angle, qreal dist) const;

    void addToSelection( Model *tModel, QString selection );
    void remFromSelection( Model *tModel, QString selection );
    void clearSupplySelectionList();
    void clearCasesSelectionList();
    QColor getColor() { return color; }
    //QString addToSelection( Model *tModel, QString selection );

private:
    MarbleWidget *widget;
    int index;
    GeoDataCoordinates coordinates;
    QList< GeoDataCoordinates> supplies;
    QList< GeoDataCoordinates> cases;
    QStringList selectionList;
    QList<QString> sTestList;
    Model *model;
    QColor color;
};

#endif  //_UIDRAWHELPER_H
