//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : E-Healthcare-Canada
//  @ File Name : DiseaseType.h
//  @ Date : 11/9/2010
//  @ Author : 
//
//


#if !defined(_DISEASETYPE_H)
#define _DISEASETYPE_H

#include <QString>


class DiseaseType
{
public:
    DiseaseType( int typeID, QString name );
    //~DiseaseType() {}
    bool overwriteWith(DiseaseType *newData);
    QString getName();
    int getTypeID();
    QString toXML();


private:
    int dTypeId;
    QString name;
};

#endif  //_DISEASETYPE_H
