//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : E-Healthcare-Canada
//  @ File Name : DiseaseCase.h
//  @ Date : 11/9/2010
//  @ Author : 
//
//


#if !defined(_DISEASECASE_H)
#define _DISEASECASE_H

#include "Trackables.h"
#include <QDate>


class DiseaseCase : public Trackables
{

private:




public:
    DiseaseCase(int id, int type, int quantity,float lon,float lat, QDate date);
    virtual ~DiseaseCase();

    // inherit the abstract function
    QString print();
    int getID();

    QString toXML();


};

#endif  //_DISEASECASE_H
