
//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : E-Healthcare-Canada
//  @ File Name : Parser.h
//  @ Date : 11/9/2010
//  @ Author : 
//
//


#if !defined(_PARSER_H)
#define _PARSER_H

#include <QtXml/QXmlSimpleReader>
#include "Handler.h"

class Parser
{
public:
        Parser();
        ~Parser();

        QXmlSimpleReader getReader();
        void parse(QString);
        UpdateReply* getUpdate();
        Reply* getReply();

private:
    QXmlSimpleReader* reader;
    UpdateReply* update;
    Reply* theReply;

};

#endif  //_PARSER_H
