//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : E-Healthcare-Canada
//  @ File Name : Supply.h
//  @ Date : 11/9/2010
//  @ Author : 
//
//


#if !defined(_SUPPLY_H)
#define _SUPPLY_H

#include "Trackables.h"
#include "City.h"

class Supply : public Trackables
{

public:
    Supply(int id,int type,int quantity,float lon = 0,float lat = 0, QDate theDate = QDate::currentDate());
    ~Supply();

    Supply(const Supply &copySupply);
    QString print();
    QString toXML();

   int getID();

private:

};

#endif  //_SUPPLY_H
