//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : E-Healthcare-Canada
//  @ File Name : Parser.cpp
//  @ Date : 11/9/2010
//  @ Author : 
//
//


#include "../Common/include/Parser.h"
#include <QtXml/QXmlSimpleReader>
#include "../Common/include/Handler.h"
#include <QDebug>


Parser::Parser() {
    reader = new QXmlSimpleReader();
}

Parser::~Parser() {
 delete reader;
}


void Parser::parse(QString msg){
    Handler h;
    QXmlInputSource input;
    input.setData(msg);
    reader->setContentHandler(&h);
    reader->parse(&input,false);
    reader->setErrorHandler(&h);
    update = h.getUpdate();
    theReply=h.getReply();
}

UpdateReply* Parser::getUpdate(){
    return update;
}

Reply* Parser::getReply(){
    return theReply;
}
