//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : E-Healthcare-Canada
//  @ File Name : ServerParser.h
//  @ Date : 11/9/2010
//  @ Author : 
//
//


#if !defined(_SERVERPARSER_H)
#define _SERVERPARSER_H

#include "Parser.h"

class ServerParser : public Parser
{
};

#endif  //_SERVERPARSER_H
